{% set name = "html5lib" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/html5lib-{{ version }}.tar.gz
  sha256: b2e5b40261e20f354d198eae92afc10d750afb487ed5e50f9c4eaf07c184146f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six >=1.9
    - webencodings

test:
  imports:
    - html5lib
    - html5lib._trie
    - html5lib.filters
    - html5lib.treeadapters
    - html5lib.treebuilders
    - html5lib.treewalkers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/html5lib/html5lib-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HTML parser based on the WHATWG HTML specification
  description: |
    html5lib is a pure-python library for parsing HTML. It is designed to
    conform to the WHATWG HTML specification, as is implemented by all major
    web browsers.
  doc_url: http://html5lib.readthedocs.org/
  doc_source_url: https://github.com/html5lib/html5lib-python/blob/master/doc/index.rst
  dev_url: https://github.com/html5lib/html5lib-python

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - ocefpaf
