travis:
  secure:
    BINSTAR_TOKEN: rvBbbl8ZbTTxi9hqn9NivffiUp+VocHfos4tKhUiSpuKjYwpZgy0idHrGvfMB9FMXyd7PsE/5gR3qQ41T273ybND//i2JnoNdC5OqPrv1DdRFzASwEWHuRT4xSuPyv2uM7LvZNh+XclOTjdh1RtxYAJoiq/vu2m8fYOjDChlaPnX01bTAVGFzbdsF9szzaJfih5dyMoliP+LagXZ7vJ6vFkAsLEGd7+usJlV8rCJcvj63dsYHuyrKpwx6r4X4qp7dkgo8kklGlNiAEE194FQdccYejpHEcOVzfdoINkOfY3tQdKFAEgXKuPhVl77/A95R4SGbiDcsGSZPPRIK8Jjys1rxJbZ8q3+sqI3V5u1SeHxUMHHs3tZkivDkJtalXZukVXIFwN9JtCoiEqLRf1E/ltyDH9vZThw4EcuV5wbjVr2UZesD8j5DfThCPSBciyveUGUIVBSVE086bUJ/F9cVPvf7DfqTIDKDT+lCtv5f3c3gK8US5zf0nWl11QUb0WjZDJqtjxn+Mnp1DLxSXndjFSXGwoyvdQSS9VRggeFu0V9PN8VTiGbEc3tCnnUFXKQeWNl+XJQA9Xa+iQzPMaPGJJsgt9ox6v6BLIY0ulgq0SloFho/7PTZwxvjWNOrfLygzlO0re5Wt3S24vxxlK8k44ViQ/cZNUYrhBrMce3Di4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
